---
env:
  NODE_REGISTRY: "https://repo.aurin.cloud.edu.au/repository/npm-aurin/"
steps:
  - label: "Linting :lint-roller:"
    command: "git diff-tree --no-commit-id --name-only -r ${BUILDKITE_COMMIT} | xargs pre-commit run --files"
  - label: "Test"
    branches: "*"
    command:
      - "npm ci"
      - "npm test"
    plugins:
      - docker#v3.7.0:
          always-pull: true
          propagate-uid-gid: true
          volumes:
            - $HOME/.npm:/.npm
            - $HOME/.npmrc:/workdir/.npmrc:ro
          image: "node:12-buster"
  #  - label: "Sonar"
  #    branches: "develop"
  #    commands:
  #      - "mvn clean verify"
  - wait
  - label: "Publish unscoped"
    branches: "develop v*.*.*"
    commands:
      - "npm install"
      # unscoped name needs sent to private repository explicitly
      - "npm publish --registry=${NODE_REGISTRY}"
    plugins:
      - docker#v3.7.0:
          always-pull: true
          propagate-uid-gid: true
          environment:
            - BUILDKITE
            - BUILDKITE_BUILD_NUMBER
            - BUILDKITE_TAG
          volumes:
            - $HOME/.npm:/.npm
            - $HOME/.npmrc:/workdir/.npmrc:ro
          image: "node:12-buster"
  - label: "Publish scoped"
    branches: "develop v*.*.*"
    commands:
      - "npm install"
      - "npm run scope"
      - "npm publish" # Scoped name uses .npmrc to find repository
    plugins:
      - docker#v3.7.0:
          always-pull: true
          propagate-uid-gid: true
          environment:
            - BUILDKITE
            - BUILDKITE_BUILD_NUMBER
            - BUILDKITE_TAG
          volumes:
            - $HOME/.npm:/.npm
            - $HOME/.npmrc:/workdir/.npmrc:ro
          image: "node:12-buster"
